name:                aoc-y2020
version:             0.1.0.0
github:              "nilsalex/aoc-y2020"
license:             MIT
author:              "Nils Alex"
maintainer:          "Nils Alex"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/aoc-y2020#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec

library:
  source-dirs: src

executables:
  aoc-y2020:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-y2020
